### ISSUE TITLE
Does a non-priority ID show up as valid?

### ISSUE THREAD

**Issue by gearsincorg** [LimelightVision/limelight-feedback#13]
The change log for 2024.1 says:

> If your priority id is not -1, tx/ty/ta will return 0 unless the chosen tag is visible.

Does this condition ALSO return a tv of 0?   It seems like it should.

**Comment by bhjelstrom** [comment]
You will in fact see a tv of zero if the priority tag is not visible. I will close this once this has been added to the docs.

Thanks!
