### ISSUE TITLE
Provide mounting dimentions drawing for LL3g

### ISSUE THREAD

**Issue by zaaj** [LimelightVision/limelight-feedback#15]
The mounting dimentions drawings on the website don't mention the 3g yet - we just ordered a couple and wanted to get our design team working on new mounts for the 2+s we're replacing

**Comment by zaaj** [comment]
ok, I see in the announcement CD post that it says:
* Threaded M3 Mount holes in addition to the standard LL3 mount holes
how about the locations of the Threaded M3 mount holes then?

**Comment by bhjelstrom** [comment]
https://docs.limelightvision.io/docs/docs-limelight/getting-started/mounting

Added here, thanks!
