### ISSUE TITLE
Update documentation to include LL3g

### ISSUE THREAD

**Issue by nihonjinrxs** [LimelightVision/limelight-feedback#16]
Documentation currently doesn't mention the LimeLight 3g at all. Hardware documentation would be helpful.

In particular, things seemingly missing are:

- documentation (including drawings/CAD models) of the hardware form factor, mounting options, and ports on the LL3g
- documentation of the buttons on the LL3g
- documentation regarding using a secondary USB camera with the LL3g

**Comment by zaaj** [comment]
They just added the drawing of the 3g
https://github.com/LimelightVision/limelight-feedback/issues/15

can't remember where I saw that it doesn't support a secondary camera.  maybe the Chief Delphi post introducing it?  Ther's no USB A port, but it does have a USB-C port that can power it from a laptop without external 12V power supply for config and testing
