### ISSUE TITLE
Improved Calibration Workflow

### ISSUE THREAD

**Issue by Gold872** [LimelightVision/limelight-feedback#17]
Currently, the workflow for the charuco camera calibration can be extremely time consuming and very slow. There's a few issues with the current system for calibrating:
1. Having to create a whole new pipeline
2. Snapshots, they can take about 0.5 seconds to take
3. No way of verifying whether or not an image is valid until images are input into calibration
4. Having to download and upload the results to actually use them

Here's my idea for a better workflow, the steps would be the following:
1. Go to a separate "Calibration" section
2. Input the size and type of calibration board
3. Adjust your resolution and exposure (this is a whole separate camera stream just for calibration, not a pipeline)
5. Hit "Record" to start capturing images
6. Move your board around to capture images at different angles and distances
7. Press "Finish Calibration", this will then process the images and display the results

When capturing all of the images, it will display an outline around each marker on the board as a way of indicating whether or not it is a valid image, this will solve the issue of not knowing whether or not your settings are correct until you try calibrating.

What could also be helpful is a way of determining whether or not the measurements the user specifies are incorrect, but that has less to do with the workflow and more to do with user error.

**Comment by bhjelstrom** [comment]
We've found that the changes in 2024.6 make calibration feel a lot better:

1. You don't need to re-enter your calibration board parameters every time you want to calibrate
2. You can now download a mosaic that shows you exactly what each image is contributing. Bad images are marked with a red outline
3. Calibration upgrades from earlier updates give you quick and accurate calibration with 15 images. 

Reasons to avoid video for now:
- Any motion blur will negatively impact results.

Reasons to force user downloads:
- We want users to have the file on their laptop. Losing a pipeline is not a big deal, but losing calibration after an image update.

Reasons to avoid a separate mode for now:
- State management - eg, do we leave calibration mode when the user closes the browser?
- Complexity - if we add new camera configuration options, do we need to support said options in the pipeline UI and in the calibration UI?

One way to improve the UX in the way you describe without ballooning the complexity would be special-casing pipeline 10 as "focus and calibration" in name only. Users switch to this pipeline (which is a regular pipeline that defaults to viewfinder mode), and they configure camera settings from there. The next steps would be locking pipeline 10 to viewfinder mode and allocating a separate directory structure for calibration images. We will look into this.

**Comment by bhjelstrom** [comment]
With the calibration mosaic, viewfinder mode, and other changes introduced earlier in the year, I'm going to close this issue for now. We have more calibration coverage metrics on the roadmap as well.
