### ISSUE TITLE
Add Corner Points Array To Limelight-Lib Java Neural Detector Results

### ISSUE THREAD

**Issue by Jelatinone** [LimelightVision/limelight-feedback#18]
The current Neural Detector Result Class: `LimelightTarget_Detector`, also found [here](https://github.com/LimelightVision/limelightlib-wpijava/blob/main/LimelightHelpers.java#L246), only supports the following values parsed from the JSON dump:
- class 
- classID
- conf
- ta
- tx
- txp
- ty
- typ

**But this type notably does not include the `pts` array as a member field**, the corner points provided from the JSON dump [X,Y] as described [here](https://docs.limelightvision.io/docs/docs-limelight/apis/json-dump-specification#neural-detector-results). I am unfamiliar with the underlying mechanics of the detector results, and the description of 'pts' does note: '...[m]ust be enabled.' **But does this prevent it from being a valid field?** Presumably the JSON parser is robust enough such that this field would simply remain an empty 2D double array, where the number of rows and columns are zero.

**Could this possibly be added as a field to the `LimelightTarget_Detector` class, as `ta`, `tx`, and `ty` (or their respective pixel variants) are insufficient for many use cases; such as determining the position of a detected object (my case).** 

I believe (though I am inexperienced in JSON parsing in Java) implementation would look something like the below code block:
```java
@JsonProperty("pts")
public double[][] pts;
```

**Comment by bhjelstrom** [comment]
We just updated the 2024.8 image (yet to be released) to populate the pts array for the detector if send corners is enabled. The library will be updated once this image is released. Thanks for your feedback.
