### ISSUE TITLE
Documentation Typo (Retroreflective Pipeline Math)

### ISSUE THREAD

**Issue by CoolSpy3** [LimelightVision/limelight-feedback#19]
The [Retroreflective & Color Pipelines > Additional Theory > Contour Filtering > From Pixels to Angles](https://docs.limelightvision.io/docs/docs-limelight/pipeline-retro/retro-theory#from-pixels-to-angles) section of the documentation has a small, but important typo. The docs say
```
ax = atan2(1,x)
ay = atan2(1,y)
```
However, because `atan2` is traditionally defined as [`\theta = atan2(y,x)`](https://en.wikipedia.org/wiki/Atan2), the arguments should be reversed to read
```
ax = atan2(x,1)
ay = atan2(y,1)
```

**Comment by bhjelstrom** [comment]
Fixed, good catch.
