### ISSUE TITLE
Camera offset ui creates offset in MT pose with no data

### ISSUE THREAD

**Issue by Jon-Zimmerman** [LimelightVision/limelight-feedback#23]
As of v. 2024.10.1 When adding a camera offset via the web UI, the MT2 data when no MT2 pose is available will return [x,y] = 0-xoffset, 0-yoffset. This makes it more difficult to filter MT2 as the expected return for no pose would be 0,0. (For example entering an offset of .4 m will say the robot is at -.4m, 0m if no MT2 pose is available.

**Comment by bhjelstrom** [comment]
Hi @Jon-Zimmerman, would you be willing to post your code? FTC, or FRC? Maybe this is an issue with our FTC SDK or SDK example project.

Testing 2024.10.1 here, both the JSON output and NetworkTables output for botpose and MT2 botpose contain all zeros when there are no detections.

Thanks!

**Comment by Jon-Zimmerman** [comment]
Thanks for checking out this issue, let me clarify what I meant a bit: 
I've been testing on a limelight that is not hooked up to a rio or a gyro, but we have seen this behavior on the physical robot as well. I've created a contrived example to show the behavior in question.

The behavior that we're finding confusing is when MT2 can see a tag that it perhaps internally determines doesn't make sense geometrically or based on the provided gyro angle, it returns a pose that is offset by the camera position offset. You can see that here in the screenshot where MT2 botpose is giving x = -0.5 (because of the user provided 0.5 camera offset). This also affects the BotPoseBlue which returns a pose near the middle of the field offset by the same camera offset. The ramification of this is that in the robot code we have to add a check to see if the limelight is giving us a pose within some tolerance of the middle of the field and reject if so. 
Perhaps I'm misunderstanding something but it seems like the desirable behavior would be for MT2 to return all zeros on the botpose and BotPoseBlue when it's unable to calculate a valid position instead of returning a position in the middle of the field that changes based on the camera offset.

![LL MT2 offset](https://github.com/user-attachments/assets/ffb92ba8-e47c-40e7-af76-2861e3979b91)

**Comment by bhjelstrom** [comment]
@Jon-Zimmerman Thanks for the detailed bug report! You were correct - we were not properly handling the geometric impossibility edge case. This is fixed in the upcoming update.
