### ISSUE TITLE
Static IP Address Not Recommended Warning

### ISSUE THREAD

**Issue by jasondaming** [LimelightVision/limelight-feedback#25]
While your documentation [here](https://docs.limelightvision.io/docs/docs-limelight/getting-started/FRC/networking) is clear that teams should start at .11 and go up from there, I think it would be a good idea if the Limelight IP address setting UI had a warning or some type of other notification that a team was setting an address outside of the recommended.

I recently had a team set to .20 and .21.  Interestingly enough .21 worked fine but .20 was clashing with the FMS and not working on field but working great in the pits.

**Comment by bhjelstrom** [comment]
https://vimeo.com/1023479602?share=copy#t=0

@jasondaming Great idea. This is included in the upcoming update.

Thanks!

**Comment by jasondaming** [comment]
Looks great!
