### ISSUE TITLE
Publish hardware metrics to network tables 

### ISSUE THREAD

**Issue by Gold872** [LimelightVision/limelight-feedback#5]
When debugging issues during/after competitions, it can be extremely helpful to know the performance metrics of the hardware. Some information that is helpful to see is CPU usage, temperature, RAM usage, and FPS. In the past I've been able to use information similar to that to troubleshoot RIO networking issues during competitions and during practice.

**Comment by bhjelstrom** [comment]
Released with 2024.1!

'hw' key in network tables, :5807/status GET Request
