### ISSUE TITLE
Make accessing the number of Vision Targets used by the MegaPose easier

### ISSUE THREAD

**Issue by jasondaming** [LimelightVision/limelight-feedback#7]
One of the key considerations for determining the accuracy of the megaPose is the number of targets in view.  This information is essential to evaluating the amount that we should trust the pose.  The only way (I believe?) to get this information is via the json string which shouldn't be required.

**Comment by bhjelstrom** [comment]
In 2024.1, all botpose arrays in networktables contain the following
[tx,ty,tz,r,p,y,latency,tagcount, max tag span in meters, average tag distance in meters, average tag area]
