### ISSUE TITLE
Unable to download pipelines

### ISSUE THREAD

**Issue by gearsincorg** [LimelightVision/limelight-feedback#9]
I'm running Ver 2024.0 on two different 2+ Limelights to do AprilTag processing.
When I hit the pipeline download button, I imediately get the standard Windows save dialog. (Using Chrome)
I choose the destination folder and hit save.

The process completes without error BUT there is no saved file.  The desination folder is empty.
If I repeat the process the auto-generated file name has (1) appended to it, as if the first file does exist.

I have searched for the file across my drive but it does not show up.

Is there a known issue with saving?  
Could there be a file attribute that is preventing me from seeing the saved file?
Is it going to a hidden location?
Am I just being dumb?

**Comment by bhjelstrom** [comment]
Windows may classify .vpr files as hidden items.

Can you try 
View > Show > Hidden items in the file explorer?

**Comment by gearsincorg** [comment]
Chrome had decided that the pipelines files were not secure for some reason.  They did not get saved, but they did exist on the browser's "downloads" list.  They had to be manually "kept" in order to be put on the drive.
